// <auto-generated />
let started = false;
let startPromise = null;
let configuredAssetBaseUrl = null;

function getAssetBaseUrl() {
  return configuredAssetBaseUrl ?? new URL("./", import.meta.url);
}

function normalizeAssetBaseUrl(assetBaseUrl) {
  if (!assetBaseUrl) {
    return new URL("./", import.meta.url);
  }

  let normalized = assetBaseUrl.trim();

  if (normalized.startsWith("public/")) {
    normalized = `/${normalized.substring("public/".length)}`;
  }

  if (
    !normalized.startsWith("/") &&
    !normalized.startsWith("./") &&
    !normalized.startsWith("../") &&
    !/^[a-z]+:/i.test(normalized)
  ) {
    normalized = `/${normalized}`;
  }

  if (!normalized.endsWith("/")) {
    normalized = `${normalized}/`;
  }

  if (/^[a-z]+:/i.test(normalized) || normalized.startsWith("./") || normalized.startsWith("../")) {
    return new URL(normalized, import.meta.url);
  }

  if (normalized.startsWith("/")) {
    if (globalThis.location?.origin) {
      return new URL(normalized, globalThis.location.origin);
    }

    const templateUrl = new URL(import.meta.url);
    return new URL(normalized, templateUrl.origin);
  }

  return new URL(normalized, import.meta.url);
}

function resolveBootResource(defaultUri) {
  return new URL(defaultUri, getAssetBaseUrl()).toString();
}

export function configureRatchetPs2Wasm(options = {}) {
  const assetBaseUrl = options.assetBaseUrl;
  configuredAssetBaseUrl = normalizeAssetBaseUrl(assetBaseUrl);
}

async function ensureBlazorScriptLoaded() {
  if (globalThis.Blazor && globalThis.DotNet) {
    return;
  }

  if (typeof document === "undefined") {
    await import(new URL("./_framework/blazor.webassembly.js", getAssetBaseUrl()).toString());
    await waitForRuntimeReady();
    return;
  }

  const existingScript = document.querySelector("script[data-ratchetps2-wasm-runtime='true']");
  if (existingScript) {
    await waitForRuntimeReady();
    return;
  }

  const script = document.createElement("script");
  script.src = new URL("./_framework/blazor.webassembly.js", getAssetBaseUrl()).toString();
  script.type = "module";
  script.autostart = false;
  script.setAttribute("autostart", "false");
  script.setAttribute("data-ratchetps2-wasm-runtime", "true");

  const loadPromise = new Promise((resolve, reject) => {
    script.addEventListener("load", resolve, { once: true });
    script.addEventListener("error", () => reject(new Error(`Failed to load Blazor runtime script from '${script.src}'.`)), { once: true });
  });

  document.head.appendChild(script);
  await loadPromise;
  await waitForRuntimeReady();
}

async function waitForRuntimeReady() {
  for (let attempt = 0; attempt < 100; attempt += 1) {
    if (globalThis.Blazor && globalThis.DotNet) {
      return;
    }

    await new Promise((resolve) => setTimeout(resolve, 10));
  }

  throw new Error("Blazor runtime loaded, but global Blazor/DotNet objects were not initialized.");
}

async function ensureStarted() {
  if (started) {
    return;
  }

  if (!startPromise) {
    startPromise = (async () => {
      await ensureBlazorScriptLoaded();
      await Blazor.start({
        loadBootResource: (_type, _name, defaultUri) => resolveBootResource(defaultUri),
      });
      started = true;
    })();
  }

  await startPromise;
}

function toUint8Array(value) {
  if (value instanceof Uint8Array) {
    return value;
  }

  if (value instanceof ArrayBuffer) {
    return new Uint8Array(value);
  }

  throw new TypeError("Expected Uint8Array or ArrayBuffer.");
}

export async function initializeRatchetPs2Wasm(options = {}) {
  configureRatchetPs2Wasm(options);
  await ensureStarted();
}

export async function getApiVersion() {
  await ensureStarted();

  return DotNet.invokeMethodAsync(
    "RatchetPs2.Wasm",
    "GetApiVersion"
  );
}

export async function convertPifToPng(pifBytes, options = {}) {
  await ensureStarted();

  const input = toUint8Array(pifBytes);
  const pngFormat = options.pngFormat ?? "rgba32";
  const doubleAlpha = options.doubleAlpha ?? false;
  return DotNet.invokeMethodAsync(
    "RatchetPs2.Wasm",
    "ConvertPifToPng",
    input,
    pngFormat,
    doubleAlpha
  );
}

export async function convertPifToPngBlob(pifBytes, options = {}) {
  await ensureStarted();

  const pngBytes = await convertPifToPng(pifBytes, options);
  return new Blob([pngBytes.slice().buffer], { type: "image/png" });
}

export async function convertPifListToPng(pifImages, options = {}) {
  await ensureStarted();

  const inputs = pifImages.map((image) => toUint8Array(image));
  const pngFormat = options.pngFormat ?? "rgba32";
  const doubleAlpha = options.doubleAlpha ?? false;
  return DotNet.invokeMethodAsync(
    "RatchetPs2.Wasm",
    "ConvertPifListToPng",
    inputs,
    pngFormat,
    doubleAlpha
  );
}

export async function convertPifListToPngBlobs(pifImages, options = {}) {
  await ensureStarted();

  const pngImages = await convertPifListToPng(pifImages, options);
  return pngImages.map((pngBytes) => new Blob([pngBytes.slice().buffer], { type: "image/png" }));
}

export async function convertPifListToPngPacked(pifImages, options = {}) {
  await ensureStarted();

  const inputs = pifImages.map((image) => toUint8Array(image));
  const pngFormat = options.pngFormat ?? "rgba32";
  const doubleAlpha = options.doubleAlpha ?? false;
  const result = await DotNet.invokeMethodAsync(
    "RatchetPs2.Wasm",
    "ConvertPifListToPngPacked",
    inputs,
    pngFormat,
    doubleAlpha
  );
  return {
    packedPngBytes: toUint8Array(result.packedPngBytes),
    pngOffsets: Int32Array.from(result.pngOffsets),
    pngLengths: Int32Array.from(result.pngLengths),
  };
}

export async function convertPifListToPngPackedBlobs(pifImages, options = {}) {
  await ensureStarted();

  const result = await convertPifListToPngPacked(pifImages, options);
  const blobs = new Array(result.pngOffsets.length);
  for (let i = 0; i < result.pngOffsets.length; i += 1) {
    const offset = result.pngOffsets[i];
    const length = result.pngLengths[i];
    const slice = result.packedPngBytes.slice(offset, offset + length);
    blobs[i] = new Blob([slice.buffer], { type: "image/png" });
  }
  return blobs;
}