// <auto-generated />
export type PngFormat = "rgba32" | "indexed8" | "indexed4";

export type MobyGame = "RC1" | "DL" | "UYA";

export type WasmByteArray = Uint8Array | number[] | string;

export interface ConvertPifToPngOptions {
  pngFormat?: PngFormat;
  doubleAlpha?: boolean;
}

export interface ExportMobyGltfOptions {
  game?: MobyGame;
  skipAnimations?: boolean;
  lod?: number;
}

export interface PackedPngBatchResult {
  packedPngBytes: Uint8Array;
  pngOffsets: Int32Array;
  pngLengths: Int32Array;
}

export interface PackedFileEntry {
  path: string;
  offset: number;
  length: number;
  contentType: string;
}

export interface PackedFilePackageResult {
  packedBytes: Uint8Array;
  entries: PackedFileEntry[];
}

export interface DlRgb96 {
  red: number;
  green: number;
  blue: number;
}

export interface DlVector3 {
  x: number;
  y: number;
  z: number;
}

export interface DlLevelSettingsChunkPlane {
  point: DlVector3;
  planeCount: number;
  normal: DlVector3;
  padding: number;
}

export interface DlLevelSettingsThirdPart {
  unknown0: number;
  unknown4: number;
  unknown8: number;
  unknownC: number;
}

export interface DlLevelSettingsRewardStats {
  xpDecayRate: number;
  xpDecayMin: number;
  boltDecayRate: number;
  boltDecayMin: number;
  unknown10: number;
  unknown14: number;
}

export interface DlLevelSettingsFifthPart {
  unknown0: number;
  mobyInstanceCount: number;
  unknown8: number;
  unknownC: number;
  unknown10: number;
  debugHitPoints: number;
}

export interface DlLevelSettings {
  backgroundColor: DlRgb96;
  fogColor: DlRgb96;
  fogNearDistance: number;
  fogFarDistance: number;
  fogNearIntensity: number;
  fogFarIntensity: number;
  deathHeight: number;
  isSphericalWorld: boolean;
  sphereCenter: DlVector3;
  shipPosition: DlVector3;
  shipRotationZ: number;
  shipPath: number;
  shipCameraCuboidStart: number;
  shipCameraCuboidEnd: number;
  padding58: number;
  chunkPlanes: DlLevelSettingsChunkPlane[];
  coreSoundsCount: number;
  thirdPartCount: number | null;
  thirdPart: DlLevelSettingsThirdPart[];
  rewardStats: DlLevelSettingsRewardStats | null;
  fifthPart: DlLevelSettingsFifthPart | null;
  debugAttackDamageLength: number;
  trailingByteLength: number;
}

export interface DlMobyInstance {
  size: number;
  mission: number;
  uid: number;
  bolts: number;
  classId: number;
  scale: number;
  drawDistance: number;
  updateDistance: number;
  unused20: number;
  unused24: number;
  position: DlVector3;
  rotation: DlVector3;
  group: number;
  isRooted: number;
  rootedDistance: number;
  unused4C: number;
  pvarIndex: number;
  occlusion: number;
  modeBits: number;
  color: DlRgb96;
  light: number;
  unused6C: number;
}

export interface DlMobyInstances {
  staticCount: number;
  spawnableMobyCount: number;
  pad8: number;
  padC: number;
  instances: DlMobyInstance[];
  trailingByteLength: number;
}

export interface DlPvarTableEntry {
  index: number;
  offset: number;
  length: number;
  data: Uint8Array;
}

export interface DlPvarRelativePointer {
  pvarIndex: number;
  offset: number;
}

export interface DlPvarTables {
  mobyLinksBytes: Uint8Array;
  tableBytes: Uint8Array;
  dataBytes: Uint8Array;
  relativePointerBytes: Uint8Array;
  entries: DlPvarTableEntry[];
  relativePointers: DlPvarRelativePointer[];
}

export interface GameplayVector3 {
  x: number;
  y: number;
  z: number;
}

export interface GameplayVector4 {
  x: number;
  y: number;
  z: number;
  w: number;
}

export interface GameplayCuboid {
  index: number;
  matrix: number[];
  inverseRotationMatrix: number[];
  rotation: GameplayVector3;
}

export interface GameplaySpline {
  index: number;
  points: GameplayVector4[];
}

export interface GameplayArea {
  index: number;
  boundingSphere: GameplayVector4;
  lastUpdateTime: number;
  splineIndices: number[];
  cuboidIndices: number[];
  sphereIndices: number[];
  cylinderIndices: number[];
  negativeCuboidIndices: number[];
}

export interface GameplayGeometry {
  cuboids: GameplayCuboid[];
  splines: GameplaySpline[];
  areas: GameplayArea[];
}

export interface DlGameplayBlock {
  index: number;
  headerOffset: number;
  pointer: number;
  semanticName: string;
  payloadLength: number;
  levelSettings: DlLevelSettings | null;
  mobyInstances: DlMobyInstances | null;
}

export interface DlGameplayBlocks {
  kind: string;
  headerSize: number;
  pvarTables: DlPvarTables | null;
  geometry: GameplayGeometry;
  blocks: DlGameplayBlock[];
}

export type UyaRgb96 = DlRgb96;

export type UyaVector3 = DlVector3;

export type UyaLevelSettingsChunkPlane = DlLevelSettingsChunkPlane;

export type UyaPvarTables = DlPvarTables;

export interface UyaLevelSettings {
  backgroundColor: UyaRgb96;
  fogColor: UyaRgb96;
  fogNearDistance: number;
  fogFarDistance: number;
  fogNearIntensity: number;
  fogFarIntensity: number;
  deathHeight: number;
  isSphericalWorld: boolean;
  sphereCenter: UyaVector3;
  shipPosition: UyaVector3;
  shipRotationZ: number;
  shipPath: number;
  shipCameraCuboidStart: number;
  shipCameraCuboidEnd: number;
  padding58: number;
  chunkPlanes: UyaLevelSettingsChunkPlane[];
  coreSoundsCount: number;
  rac3ThirdPart: number;
  trailingByteLength: number;
}

export interface UyaMobyInstance {
  size: number;
  mission: number;
  unknown8: number;
  unknownC: number;
  uid: number;
  bolts: number;
  unknown18: number;
  unknown1C: number;
  unknown20: number;
  unknown24: number;
  classId: number;
  scale: number;
  drawDistance: number;
  updateDistance: number;
  unused38: number;
  unused3C: number;
  position: UyaVector3;
  rotation: UyaVector3;
  group: number;
  isRooted: number;
  rootedDistance: number;
  unknown64: number;
  pvarIndex: number;
  occlusion: number;
  modeBits: number;
  color: UyaRgb96;
  light: number;
  unknown84: number;
}

export interface UyaMobyInstances {
  staticCount: number;
  spawnableMobyCount: number;
  pad8: number;
  padC: number;
  instances: UyaMobyInstance[];
  trailingByteLength: number;
}

export interface UyaGameplayBlock {
  index: number;
  headerOffset: number;
  pointer: number;
  semanticName: string;
  payloadLength: number;
  payloadBytes: Uint8Array;
  levelSettings: UyaLevelSettings | null;
  mobyInstances: UyaMobyInstances | null;
}

export interface UyaGameplayBlocks {
  kind: string;
  headerSize: number;
  headerBytes: Uint8Array;
  pvarTables: UyaPvarTables | null;
  geometry: GameplayGeometry;
  blocks: UyaGameplayBlock[];
}

export interface RatchetPs2WasmInitOptions {
  assetBaseUrl?: string;
}

export function configureRatchetPs2Wasm(options?: RatchetPs2WasmInitOptions): void;

export function initializeRatchetPs2Wasm(options?: RatchetPs2WasmInitOptions): Promise<void>;

export function getApiVersion(): Promise<string>;

export function convertPifToPng(pifBytes: Uint8Array | ArrayBuffer, options?: ConvertPifToPngOptions): Promise<Uint8Array>;

export function convertPifToPngBlob(pifBytes: Uint8Array | ArrayBuffer, options?: ConvertPifToPngOptions): Promise<Blob>;

export function convertPifListToPng(pifImages: Array<Uint8Array | ArrayBuffer>, options?: ConvertPifToPngOptions): Promise<Uint8Array[]>;

export function convertPifListToPngBlobs(pifImages: Array<Uint8Array | ArrayBuffer>, options?: ConvertPifToPngOptions): Promise<Blob[]>;

export function convertPifListToPngPacked(pifImages: Array<Uint8Array | ArrayBuffer>, options?: ConvertPifToPngOptions): Promise<PackedPngBatchResult>;

export function convertPifListToPngPackedBlobs(pifImages: Array<Uint8Array | ArrayBuffer>, options?: ConvertPifToPngOptions): Promise<Blob[]>;

export function unpackDlLevelWad(levelWadBytes: Uint8Array | ArrayBuffer): Promise<PackedFilePackageResult>;

export function unpackUyaLevelWad(levelWadBytes: Uint8Array | ArrayBuffer): Promise<PackedFilePackageResult>;

export function exportMobyGltf(mobyBytes: Uint8Array | ArrayBuffer, options?: ExportMobyGltfOptions): Promise<PackedFilePackageResult>;

export function parseDlGameplayCore(gameplayBytes: Uint8Array | ArrayBuffer): Promise<DlGameplayBlocks>;

export function parseRc1GameplayCore(gameplayBytes: Uint8Array | ArrayBuffer): Promise<DlGameplayBlocks>;

export function parseDlGameplayMission(gameplayBytes: Uint8Array | ArrayBuffer): Promise<DlGameplayBlocks>;

export function parseGcGameplayCore(gameplayBytes: Uint8Array | ArrayBuffer): Promise<UyaGameplayBlocks>;

export function parseUyaGameplayCore(gameplayBytes: Uint8Array | ArrayBuffer): Promise<UyaGameplayBlocks>;

export function buildDlLevelWadRenderPackage(levelWadBytes: Uint8Array | ArrayBuffer): Promise<PackedFilePackageResult>;

export function buildDlLevelWadRenderPackageEnvelope(levelWadBytes: Uint8Array | ArrayBuffer): Promise<WasmByteArray>;

export function buildGcLevelWadRenderPackage(levelWadBytes: Uint8Array | ArrayBuffer): Promise<PackedFilePackageResult>;

export function buildRc1LevelWadRenderPackage(levelWadBytes: Uint8Array | ArrayBuffer): Promise<PackedFilePackageResult>;

export function buildRc1LevelWadRenderPackageEnvelope(levelWadBytes: Uint8Array | ArrayBuffer): Promise<WasmByteArray>;

export function buildGcLevelWadRenderPackageEnvelope(levelWadBytes: Uint8Array | ArrayBuffer): Promise<WasmByteArray>;

export function buildUyaLevelWadRenderPackage(levelWadBytes: Uint8Array | ArrayBuffer): Promise<PackedFilePackageResult>;

export function buildUyaLevelWadRenderPackageEnvelope(levelWadBytes: Uint8Array | ArrayBuffer): Promise<WasmByteArray>;

export function buildUyaCustomMapZipRenderPackage(zipBytes: Uint8Array | ArrayBuffer): Promise<PackedFilePackageResult>;

export function buildUyaCustomMapZipRenderPackageEnvelope(zipBytes: Uint8Array | ArrayBuffer): Promise<WasmByteArray>;