// <auto-generated />
export type PngFormat = "rgba32" | "indexed8" | "indexed4";

export interface ConvertPifToPngOptions {
  pngFormat?: PngFormat;
  doubleAlpha?: boolean;
}

export interface PackedPngBatchResult {
  packedPngBytes: Uint8Array;
  pngOffsets: Int32Array;
  pngLengths: Int32Array;
}

export interface RatchetPs2WasmInitOptions {
  assetBaseUrl?: string;
}

export function configureRatchetPs2Wasm(options?: RatchetPs2WasmInitOptions): void;

export function initializeRatchetPs2Wasm(options?: RatchetPs2WasmInitOptions): Promise<void>;

export function getApiVersion(): Promise<string>;

export function convertPifToPng(pifBytes: Uint8Array | ArrayBuffer, options?: ConvertPifToPngOptions): Promise<Uint8Array>;

export function convertPifToPngBlob(pifBytes: Uint8Array | ArrayBuffer, options?: ConvertPifToPngOptions): Promise<Blob>;

export function convertPifListToPng(pifImages: Array<Uint8Array | ArrayBuffer>, options?: ConvertPifToPngOptions): Promise<Uint8Array[]>;

export function convertPifListToPngBlobs(pifImages: Array<Uint8Array | ArrayBuffer>, options?: ConvertPifToPngOptions): Promise<Blob[]>;

export function convertPifListToPngPacked(pifImages: Array<Uint8Array | ArrayBuffer>, options?: ConvertPifToPngOptions): Promise<PackedPngBatchResult>;

export function convertPifListToPngPackedBlobs(pifImages: Array<Uint8Array | ArrayBuffer>, options?: ConvertPifToPngOptions): Promise<Blob[]>;